
/**
 * FacturacionSkeleton.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis2 version: 1.6.3  Built on : Jun 27, 2015 (11:17:49 BST)
 */
package org.mtis.www.facturacion;

import java.io.FileOutputStream;
import java.util.Date;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;

/**
 * FacturacionSkeleton java skeleton for the axisService
 */
public class FacturacionSkeleton {

	/**
	 * Auto generated method signature
	 * 
	 * @param crearFactura
	 * @return crearFacturaResponse
	 */
	
	private static Font catFont = new Font(Font.FontFamily.TIMES_ROMAN, 18,
            Font.BOLD);
    private static Font smallBold = new Font(Font.FontFamily.TIMES_ROMAN, 12,
            Font.BOLD);

	private static void addEmptyLine(Paragraph paragraph, int number) {
		for (int i = 0; i < number; i++) {
			paragraph.add(new Paragraph(" "));
		}
	}

	private static void addContent(Document document, String nombre, int precio, int unidades) throws DocumentException {
		Paragraph content = new Paragraph();
		// We add one empty line
		addEmptyLine(content, 1);
		// Lets write a big header
		content.add(new Paragraph("Paquetes contratados", catFont));
		addEmptyLine(content, 2);
		content.add(new Paragraph(nombre + " precio: " + precio + " unidades " + unidades, catFont));
		
		document.add(content);
	}
	
	private static void addTitlePage(Document document, int idReserva) throws DocumentException {
		Paragraph preface = new Paragraph();
		// We add one empty line
		addEmptyLine(preface, 1);
		// Lets write a big header
		preface.add(new Paragraph("Reserva Paquete Vacacional", catFont));

		addEmptyLine(preface, 1);
		// Will create: Report generated by: _name, _date
		preface.add(new Paragraph("Factura generada el  " + new Date(),smallBold));
		addEmptyLine(preface, 3);
		preface.add(new Paragraph("Factura asociada a la reserva con ID " + idReserva, smallBold));
		addEmptyLine(preface,4);
		document.add(preface);
	
	}

	public org.mtis.www.facturacion.CrearFacturaResponse crearFactura(
			org.mtis.www.facturacion.CrearFactura crearFactura) {

		CrearFacturaResponse response = new CrearFacturaResponse();
		Document document = new Document();
		try {

			PdfWriter.getInstance(document, new FileOutputStream("D:/factura.pdf"));

			document.open();
			addTitlePage(document, crearFactura.getIdReserva());
			addContent(document,"nombre paquete vacacional", 105, 2);
			response.setCreada(true);
		} catch (Exception e) {
			response.setCreada(false);
			response.setCodigoError(400);
			e.printStackTrace();
		} finally {
			document.close();
		}

		return response;
	}



}
